version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DOCKER_BUILDKIT: '1'
    container_name: cmg-api-prod
    env_file:
      - .env.production
    ports:
      - '1000:6060'
    depends_on:
      - postgres
      - redis

  postgres:
    container_name: cmg-db-prod
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=cmgapi'
      - 'POSTGRES_PASSWORD=localpassword'
      - 'POSTGRES_USER=cmgapi'
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
      - ./docker/postgres/log:/var/log/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}']
      interval: 10s
      timeout: 10s
      retries: 5
    ports:
      - '1001:5432'

  redis:
    container_name: cmg-redis-prod
    image: 'redis:latest'
    ports:
      - '1002:6379'

networks:
  default:
    external:
      name: nginx_webnet
