name: cmg-backend-prod

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - 'DOCKER_BUILDKIT=1'
    container_name: cmg-api-prod
    env_file:
      - env/prod/prod.env
    ports:
      - '1000:6060'
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres:
    container_name: cmg-db-prod
    image: 'postgres:latest'
    env_file:
      - env/prod/db.prod.env
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
      - ./docker/postgres/log:/var/log/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}']
      interval: 10s
      timeout: 10s
      retries: 5
    ports:
      - '1001:5432'

  redis:
    container_name: cmg-redis-prod
    image: 'redis:latest'
    ports:
      - '1002:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  default:
    external: true
    name: nginx_webnet
