export const countries = [
  { name: 'Afghanistan', shortCode: 'AF', code: 'AFG', continent: 'asia' },
  { name: 'Åland Islands', shortCode: 'AX', code: 'ALA', continent: 'europe' },
  { name: 'Albania', shortCode: 'AL', code: 'ALB', continent: 'europe' },
  { name: 'Algeria', shortCode: 'DZ', code: 'DZA', continent: 'africa' },
  {
    name: 'American Samoa',
    shortCode: 'AS',
    code: 'ASM',
    continent: 'oceania',
  },
  { name: 'Andorra', shortCode: 'AD', code: 'AND', continent: 'europe' },
  { name: 'Angola', shortCode: 'AO', code: 'AGO', continent: 'africa' },
  { name: 'Anguilla', shortCode: 'AI', code: 'AIA', continent: 'america' },
  { name: 'Antarctica', shortCode: 'AQ', code: 'ATA', continent: 'oceania' },
  {
    name: 'Antigua and Barbuda',
    shortCode: 'AG',
    code: 'ATG',
    continent: 'america',
  },
  { name: 'Argentina', shortCode: 'AR', code: 'ARG', continent: 'america' },
  { name: 'Armenia', shortCode: 'AM', code: 'ARM', continent: 'asia' },
  { name: 'Aruba', shortCode: 'AW', code: 'ABW', continent: 'america' },
  { name: 'Australia', shortCode: 'AU', code: 'AUS', continent: 'oceania' },
  { name: 'Austria', shortCode: 'AT', code: 'AUT', continent: 'europe' },
  { name: 'Azerbaijan', shortCode: 'AZ', code: 'AZE', continent: 'asia' },
  { name: 'Bahamas', shortCode: 'BS', code: 'BHS', continent: 'america' },
  { name: 'Bahrain', shortCode: 'BH', code: 'BHR', continent: 'asia' },
  { name: 'Bangladesh', shortCode: 'BD', code: 'BGD', continent: 'asia' },
  { name: 'Barbados', shortCode: 'BB', code: 'BRB', continent: 'america' },
  { name: 'Belarus', shortCode: 'BY', code: 'BLR', continent: 'europe' },
  { name: 'Belgium', shortCode: 'BE', code: 'BEL', continent: 'europe' },
  { name: 'Belize', shortCode: 'BZ', code: 'BLZ', continent: 'america' },
  { name: 'Benin', shortCode: 'BJ', code: 'BEN', continent: 'africa' },
  { name: 'Bermuda', shortCode: 'BM', code: 'BMU', continent: 'america' },
  { name: 'Bhutan', shortCode: 'BT', code: 'BTN', continent: 'asia' },
  { name: 'Bolivia', shortCode: 'BO', code: 'BOL', continent: 'america' },
  {
    name: 'Bosnia and Herzegovina',
    shortCode: 'BA',
    code: 'BIH',
    continent: 'europe',
  },
  { name: 'Botswana', shortCode: 'BW', code: 'BWA', continent: 'africa' },
  { name: 'Bouvet Island', shortCode: 'BV', code: 'BVT', continent: 'oceania' },
  { name: 'Brazil', shortCode: 'BR', code: 'BRA', continent: 'america' },
  {
    name: 'British Indian Ocean Territory',
    shortCode: 'IO',
    code: 'IOT',
    continent: 'asia',
  },
  {
    name: 'Brunei Darussalam',
    shortCode: 'BN',
    code: 'BRN',
    continent: 'asia',
  },
  { name: 'Bulgaria', shortCode: 'BG', code: 'BGR', continent: 'europe' },
  { name: 'Burkina Faso', shortCode: 'BF', code: 'BFA', continent: 'africa' },
  { name: 'Burundi', shortCode: 'BI', code: 'BDI', continent: 'africa' },
  { name: 'Cambodia', shortCode: 'KH', code: 'KHM', continent: 'asia' },
  { name: 'Cameroon', shortCode: 'CM', code: 'CMR', continent: 'africa' },
  { name: 'Canada', shortCode: 'CA', code: 'CAN', continent: 'america' },
  { name: 'Cape Verde', shortCode: 'CV', code: 'CPV', continent: 'africa' },
  {
    name: 'Cayman Islands',
    shortCode: 'KY',
    code: 'CYM',
    continent: 'america',
  },
  {
    name: 'Central African Republic',
    shortCode: 'CF',
    code: 'CAF',
    continent: 'africa',
  },
  { name: 'Chad', shortCode: 'TD', code: 'TCD', continent: 'africa' },
  { name: 'Chile', shortCode: 'CL', code: 'CHL', continent: 'america' },
  { name: 'China', shortCode: 'CN', code: 'CHN', continent: 'asia' },
  {
    name: 'Christmas Island',
    shortCode: 'CX',
    code: 'CXR',
    continent: 'oceania',
  },
  {
    name: 'Cocos (Keeling) Islands',
    shortCode: 'CC',
    code: 'CCK',
    continent: 'oceania',
  },
  { name: 'Colombia', shortCode: 'CO', code: 'COL', continent: 'america' },
  { name: 'Comoros', shortCode: 'KM', code: 'COM', continent: 'africa' },
  { name: 'Congo', shortCode: 'CG', code: 'COG', continent: 'africa' },
  {
    name: 'Congo, Democratic Republic of the',
    shortCode: 'CD',
    code: 'COD',
    continent: 'africa',
  },
  { name: 'Cook Islands', shortCode: 'CK', code: 'COK', continent: 'america' },
  { name: 'Costa Rica', shortCode: 'CR', code: 'CRI', continent: 'america' },
  { name: "Côte d'Ivoire", shortCode: 'CI', code: 'CIV', continent: 'africa' },
  { name: 'Croatia', shortCode: 'HR', code: 'HRV', continent: 'europe' },
  { name: 'Cuba', shortCode: 'CU', code: 'CUB', continent: 'america' },
  { name: 'Cyprus', shortCode: 'CY', code: 'CYP', continent: 'europe' },
  { name: 'Czech Republic', shortCode: 'CZ', code: 'CZE', continent: 'europe' },
  { name: 'Denmark', shortCode: 'DK', code: 'DNK', continent: 'europe' },
  { name: 'Djibouti', shortCode: 'DJ', code: 'DJI', continent: 'africa' },
  { name: 'Dominica', shortCode: 'DM', code: 'DMA', continent: 'america' },
  {
    name: 'Dominican Republic',
    shortCode: 'DO',
    code: 'DOM',
    continent: 'america',
  },
  { name: 'Ecuador', shortCode: 'EC', code: 'ECU', continent: 'america' },
  { name: 'Egypt', shortCode: 'EG', code: 'EGY', continent: 'africa' },
  { name: 'El Salvador', shortCode: 'SV', code: 'SLV', continent: 'america' },
  {
    name: 'Equatorial Guinea',
    shortCode: 'GQ',
    code: 'GNQ',
    continent: 'africa',
  },
  { name: 'Eritrea', shortCode: 'ER', code: 'ERI', continent: 'africa' },
  { name: 'Estonia', shortCode: 'EE', code: 'EST', continent: 'europe' },
  { name: 'Ethiopia', shortCode: 'ET', code: 'ETH', continent: 'africa' },
  {
    name: 'Falkland Islands (Malvinas)',
    shortCode: 'FK',
    code: 'FLK',
    continent: 'america',
  },
  { name: 'Faroe Islands', shortCode: 'FO', code: 'FRO', continent: 'europe' },
  {
    name: 'Fiji',
    shortCode: 'FJ',
    code: 'FJI',

    continent: 'oceania',
  },
  { name: 'Finland', shortCode: 'FI', code: 'FIN', continent: 'europe' },
  { name: 'France', shortCode: 'FR', code: 'FRA', continent: 'europe' },
  { name: 'French Guiana', shortCode: 'GF', code: 'GUF', continent: 'america' },
  {
    name: 'French Polynesia',
    shortCode: 'PF',
    code: 'PYF',
    continent: 'oceania',
  },
  {
    name: 'French Southern Territories',
    shortCode: 'TF',
    code: 'ATF',
    continent: 'oceania',
  },
  { name: 'Gabon', shortCode: 'GA', code: 'GAB', continent: 'africa' },
  { name: 'Gambia', shortCode: 'GM', code: 'GMB', continent: 'africa' },
  { name: 'Georgia', shortCode: 'GE', code: 'GEO', continent: 'asia' },
  { name: 'Germany', shortCode: 'DE', code: 'DEU', continent: 'europe' },
  { name: 'Ghana', shortCode: 'GH', code: 'GHA', continent: 'africa' },
  { name: 'Gibraltar', shortCode: 'GI', code: 'GIB', continent: 'europe' },
  { name: 'Greece', shortCode: 'GR', code: 'GRC', continent: 'europe' },
  { name: 'Greenland', shortCode: 'GL', code: 'GRL', continent: 'america' },
  { name: 'Grenada', shortCode: 'GD', code: 'GRD', continent: 'america' },
  { name: 'Guadeloupe', shortCode: 'GP', code: 'GLP', continent: 'america' },
  { name: 'Guam', shortCode: 'GU', code: 'GUM', continent: 'oceania' },
  { name: 'Guatemala', shortCode: 'GT', code: 'GTM', continent: 'america' },
  { name: 'Guernsey', shortCode: 'GG', code: 'GGY', continent: 'europe' },
  { name: 'Guinea-Bissau', shortCode: 'GW', code: 'GNB', continent: 'africa' },
  { name: 'Guinea', shortCode: 'GN', code: 'GIN', continent: 'africa' },
  { name: 'Guyana', shortCode: 'GY', code: 'GUY', continent: 'america' },
  { name: 'Haiti', shortCode: 'HT', code: 'HTI', continent: 'america' },
  {
    name: 'Heard Island and McDonald Islands',
    shortCode: 'HM',
    code: 'HMD',
    continent: 'oceania',
  },
  {
    name: 'Holy See (Vatican City State)',
    shortCode: 'VA',
    code: 'VAT',
    continent: 'europe',
  },
  { name: 'Honduras', shortCode: 'HN', code: 'HND', continent: 'america' },
  { name: 'Hong Kong', shortCode: 'HK', code: 'HKG', continent: 'asia' },
  { name: 'Hungary', shortCode: 'HU', code: 'HUN', continent: 'europe' },
  { name: 'Iceland', shortCode: 'IS', code: 'ISL', continent: 'europe' },
  { name: 'India', shortCode: 'IN', code: 'IND', continent: 'asia' },
  { name: 'Indonesia', shortCode: 'ID', code: 'IDN', continent: 'asia' },
  {
    name: 'Iran, Islamic Republic of',
    shortCode: 'IR',
    code: 'IRN',
    continent: 'asia',
  },
  { name: 'Iraq', shortCode: 'IQ', code: 'IRQ', continent: 'asia' },
  { name: 'Ireland', shortCode: 'IE', code: 'IRL', continent: 'europe' },
  { name: 'Isle of Man', shortCode: 'IM', code: 'IMN', continent: 'europe' },
  { name: 'Israel', shortCode: 'IL', code: 'ISR', continent: 'asia' },
  { name: 'Italy', shortCode: 'IT', code: 'ITA', continent: 'europe' },
  { name: 'Jamaica', shortCode: 'JM', code: 'JAM', continent: 'america' },
  { name: 'Japan', shortCode: 'JP', code: 'JPN', continent: 'asia' },
  { name: 'Jersey', shortCode: 'JE', code: 'JEY', continent: 'europe' },
  { name: 'Jordan', shortCode: 'JO', code: 'JOR', continent: 'asia' },
  { name: 'Kazakhstan', shortCode: 'KZ', code: 'KAZ', continent: 'asia' },
  { name: 'Kenya', shortCode: 'KE', code: 'KEN', continent: 'africa' },
  { name: 'Kiribati', shortCode: 'KI', code: 'KIR', continent: 'oceania' },
  {
    name: "Korea, Democratic People's Republic of",
    shortCode: 'KP',
    code: 'PRK',
    continent: 'asia',
  },
  {
    name: 'Korea, Republic of',
    shortCode: 'KR',
    code: 'KOR',
    continent: 'asia',
  },
  { name: 'Kuwait', shortCode: 'KW', code: 'KWT', continent: 'asia' },
  { name: 'Kyrgyzstan', shortCode: 'KG', code: 'KGZ', continent: 'asia' },
  {
    name: "Lao People's Democratic Republic",
    shortCode: 'LA',
    code: 'LAO',
    continent: 'asia',
  },
  { name: 'Latvia', shortCode: 'LV', code: 'LVA', continent: 'europe' },
  { name: 'Lebanon', shortCode: 'LB', code: 'LBN', continent: 'asia' },
  { name: 'Lesotho', shortCode: 'LS', code: 'LSO', continent: 'africa' },
  { name: 'Liberia', shortCode: 'LR', code: 'LBR', continent: 'africa' },
  {
    name: 'Libyan Arab Jamahiriya',
    shortCode: 'LY',
    code: 'LBY',
    continent: 'africa',
  },
  { name: 'Liechtenstein', shortCode: 'LI', code: 'LIE', continent: 'europe' },
  { name: 'Lithuania', shortCode: 'LT', code: 'LTU', continent: 'europe' },
  { name: 'Luxembourg', shortCode: 'LU', code: 'LUX', continent: 'europe' },
  { name: 'Macao', shortCode: 'MO', code: 'MAC', continent: 'asia' },
  {
    name: 'North Macedonia',
    shortCode: 'MK',
    code: 'MKD',
    continent: 'europe',
  },
  { name: 'Madagascar', shortCode: 'MG', code: 'MDG', continent: 'africa' },
  { name: 'Malawi', shortCode: 'MW', code: 'MWI', continent: 'africa' },
  { name: 'Malaysia', shortCode: 'MY', code: 'MYS', continent: 'asia' },
  { name: 'Maldives', shortCode: 'MV', code: 'MDV', continent: 'asia' },
  { name: 'Mali', shortCode: 'ML', code: 'MLI', continent: 'africa' },
  { name: 'Malta', shortCode: 'MT', code: 'MLT', continent: 'europe' },
  {
    name: 'Marshall Islands',
    shortCode: 'MH',
    code: 'MHL',
    continent: 'oceania',
  },
  { name: 'Martinique', shortCode: 'MQ', code: 'MTQ', continent: 'america' },
  { name: 'Mauritania', shortCode: 'MR', code: 'MRT', continent: 'africa' },
  { name: 'Mauritius', shortCode: 'MU', code: 'MUS', continent: 'africa' },
  { name: 'Mayotte', shortCode: 'YT', code: 'MYT', continent: 'africa' },
  { name: 'Mexico', shortCode: 'MX', code: 'MEX', continent: 'america' },
  {
    name: 'Micronesia, Federated States of',
    shortCode: 'FM',
    code: 'FSM',
    continent: 'oceania',
  },
  {
    name: 'Moldova, Republic of',
    shortCode: 'MD',
    code: 'MDA',
    continent: 'europe',
  },
  { name: 'Monaco', shortCode: 'MC', code: 'MCO', continent: 'europe' },
  { name: 'Mongolia', shortCode: 'MN', code: 'MNG', continent: 'asia' },
  { name: 'Montenegro', shortCode: 'ME', code: 'MNE', continent: 'europe' },
  { name: 'Montserrat', shortCode: 'MS', code: 'MSR', continent: 'america' },
  { name: 'Morocco', shortCode: 'MA', code: 'MAR', continent: 'africa' },
  { name: 'Mozambique', shortCode: 'MZ', code: 'MOZ', continent: 'africa' },
  { name: 'Myanmar', shortCode: 'MM', code: 'MMR', continent: 'asia' },
  { name: 'Namibia', shortCode: 'NA', code: 'NAM', continent: 'africa' },
  { name: 'Nauru', shortCode: 'NR', code: 'NRU', continent: 'oceania' },
  { name: 'Nepal', shortCode: 'NP', code: 'NPL', continent: 'asia' },
  { name: 'Netherlands', shortCode: 'NL', code: 'NLD', continent: 'europe' },
  { name: 'New Caledonia', shortCode: 'NC', code: 'NCL', continent: 'oceania' },
  { name: 'New Zealand', shortCode: 'NZ', code: 'NZL', continent: 'oceania' },
  { name: 'Nicaragua', shortCode: 'NI', code: 'NIC', continent: 'america' },
  { name: 'Niger', shortCode: 'NE', code: 'NER', continent: 'africa' },
  { name: 'Nigeria', shortCode: 'NG', code: 'NGA', continent: 'africa' },
  { name: 'Niue', shortCode: 'NU', code: 'NIU', continent: 'oceania' },
  {
    name: 'Norfolk Island',
    shortCode: 'NF',
    code: 'NFK',
    continent: 'oceania',
  },
  {
    name: 'Northern Mariana Islands',
    shortCode: 'MP',
    code: 'MNP',
    continent: 'oceania',
  },
  { name: 'Norway', shortCode: 'NO', code: 'NOR', continent: 'europe' },
  { name: 'Oman', shortCode: 'OM', code: 'OMN', continent: 'asia' },
  { name: 'Pakistan', shortCode: 'PK', code: 'PAK', continent: 'asia' },
  { name: 'Palau', shortCode: 'PW', code: 'PLW', continent: 'oceania' },
  {
    name: 'Palestinian Territory, Occupied',
    shortCode: 'PS',
    code: 'PSE',
    continent: 'asia',
  },
  { name: 'Panama', shortCode: 'PA', code: 'PAN', continent: 'america' },
  {
    name: 'Papua New Guinea',
    shortCode: 'PG',
    code: 'PNG',
    continent: 'oceania',
  },
  { name: 'Paraguay', shortCode: 'PY', code: 'PRY', continent: 'america' },
  { name: 'Peru', shortCode: 'PE', code: 'PER', continent: 'america' },
  { name: 'Philippines', shortCode: 'PH', code: 'PHL', continent: 'asia' },
  { name: 'Pitcairn', shortCode: 'PN', code: 'PCN', continent: 'oceania' },
  { name: 'Poland', shortCode: 'PL', code: 'POL', continent: 'europe' },
  { name: 'Portugal', shortCode: 'PT', code: 'PRT', continent: 'europe' },
  { name: 'Puerto Rico', shortCode: 'PR', code: 'PRI', continent: 'america' },
  { name: 'Qatar', shortCode: 'QA', code: 'QAT', continent: 'asia' },
  { name: 'Réunion', shortCode: 'RE', code: 'REU', continent: 'africa' },
  { name: 'Romania', shortCode: 'RO', code: 'ROU', continent: 'europe' },
  {
    name: 'Russian Federation',
    shortCode: 'RU',
    code: 'RUS',
    continent: 'europe',
  },
  { name: 'Rwanda', shortCode: 'RW', code: 'RWA', continent: 'africa' },
  {
    name: 'Saint Barthélemy',
    shortCode: 'BL',
    code: 'BLM',
    continent: 'america',
  },
  {
    name: 'Saint Helena, Ascension and Tristan da Cunha',
    shortCode: 'SH',
    code: 'SHN',
    continent: 'africa',
  },
  {
    name: 'Saint Kitts and Nevis',
    shortCode: 'KN',
    code: 'KNA',
    continent: 'america',
  },
  { name: 'Saint Lucia', shortCode: 'LC', code: 'LCA', continent: 'america' },
  {
    name: 'Saint Martin (French part)',
    shortCode: 'MF',
    code: 'MAF',
    continent: 'america',
  },
  {
    name: 'Saint Pierre and Miquelon',
    shortCode: 'PM',
    code: 'SPM',
    continent: 'america',
  },
  {
    name: 'Saint Vincent and the Grenadines',
    shortCode: 'VC',
    code: 'VCT',
    continent: 'america',
  },
  { name: 'Samoa', shortCode: 'WS', code: 'WSM', continent: 'oceania' },
  { name: 'San Marino', shortCode: 'SM', code: 'SMR', continent: 'europe' },
  {
    name: 'Sao Tome and Principe',
    shortCode: 'ST',
    code: 'STP',
    continent: 'africa',
  },
  { name: 'Saudi Arabia', shortCode: 'SA', code: 'SAU', continent: 'asia' },
  { name: 'Senegal', shortCode: 'SN', code: 'SEN', continent: 'africa' },
  { name: 'Serbia', shortCode: 'RS', code: 'SRB', continent: 'europe' },
  { name: 'Seychelles', shortCode: 'SC', code: 'SYC', continent: 'africa' },
  { name: 'Sierra Leone', shortCode: 'SL', code: 'SLE', continent: 'africa' },
  { name: 'Singapore', shortCode: 'SG', code: 'SGP', continent: 'asia' },
  {
    name: 'Sint Maarten (Dutch part)',
    shortCode: 'SX',
    code: 'SXM',
    continent: 'america',
  },
  { name: 'Slovakia', shortCode: 'SK', code: 'SVK', continent: 'europe' },
  { name: 'Slovenia', shortCode: 'SI', code: 'SVN', continent: 'europe' },
  {
    name: 'Solomon Islands',
    shortCode: 'SB',
    code: 'SLB',
    continent: 'oceania',
  },
  { name: 'Somalia', shortCode: 'SO', code: 'SOM', continent: 'africa' },
  { name: 'South Africa', shortCode: 'ZA', code: 'ZAF', continent: 'africa' },
  {
    name: 'South Georgia and the South Sandwich Islands',
    shortCode: 'GS',
    code: 'SGS',
    continent: 'america',
  },
  { name: 'South Sudan', shortCode: 'SS', code: 'SSD', continent: 'africa' },
  { name: 'Spain', shortCode: 'ES', code: 'ESP', continent: 'europe' },
  { name: 'Sri Lanka', shortCode: 'LK', code: 'LKA', continent: 'asia' },
  { name: 'Sudan', shortCode: 'SD', code: 'SDN', continent: 'africa' },
  { name: 'Suriname', shortCode: 'SR', code: 'SUR', continent: 'america' },
  {
    name: 'Svalbard and Jan Mayen',
    shortCode: 'SJ',
    code: 'SJM',
    continent: 'europe',
  },
  { name: 'Swaziland', shortCode: 'SZ', code: 'SWZ', continent: 'africa' },
  { name: 'Sweden', shortCode: 'SE', code: 'SWE', continent: 'europe' },
  { name: 'Switzerland', shortCode: 'CH', code: 'CHE', continent: 'europe' },
  {
    name: 'Syrian Arab Republic',
    shortCode: 'SY',
    code: 'SYR',
    continent: 'asia',
  },
  {
    name: 'Taiwan, Province of China',
    shortCode: 'TW',
    code: 'TWN',
    continent: 'asia',
  },
  { name: 'Tajikistan', shortCode: 'TJ', code: 'TJK', continent: 'asia' },
  {
    name: 'Tanzania, United Republic of',
    shortCode: 'TZ',
    code: 'TZA',
    continent: 'africa',
  },
  { name: 'Thailand', shortCode: 'TH', code: 'THA', continent: 'asia' },
  { name: 'Timor-Leste', shortCode: 'TL', code: 'TLS', continent: 'asia' },
  { name: 'Togo', shortCode: 'TG', code: 'TGO', continent: 'africa' },
  { name: 'Tokelau', shortCode: 'TK', code: 'TKL', continent: 'oceania' },
  { name: 'Tonga', shortCode: 'TO', code: 'TON', continent: 'oceania' },
  {
    name: 'Trinidad and Tobago',
    shortCode: 'TT',
    code: 'TTO',
    continent: 'america',
  },
  { name: 'Tunisia', shortCode: 'TN', code: 'TUN', continent: 'africa' },
  { name: 'Turkey', shortCode: 'TR', code: 'TUR', continent: 'asia' },
  { name: 'Turkmenistan', shortCode: 'TM', code: 'TKM', continent: 'asia' },
  {
    name: 'Turks and Caicos Islands',
    shortCode: 'TC',
    code: 'TCA',
    continent: 'america',
  },
  { name: 'Tuvalu', shortCode: 'TV', code: 'TUV', continent: 'oceania' },
  { name: 'Uganda', shortCode: 'UG', code: 'UGA', continent: 'africa' },
  { name: 'Ukraine', shortCode: 'UA', code: 'UKR', continent: 'europe' },
  {
    name: 'United Arab Emirates',
    shortCode: 'AE',
    code: 'ARE',
    continent: 'asia',
  },
  { name: 'United Kingdom', shortCode: 'GB', code: 'GBR', continent: 'europe' },
  { name: 'United States', shortCode: 'US', code: 'USA', continent: 'america' },
  {
    name: 'United States Minor Outlying Islands',
    shortCode: 'UM',
    code: 'UMI',
    continent: 'oceania',
  },
  { name: 'Uruguay', shortCode: 'UY', code: 'URY', continent: 'america' },
  { name: 'Uzbekistan', shortCode: 'UZ', code: 'UZB', continent: 'asia' },
  { name: 'Vanuatu', shortCode: 'VU', code: 'VUT', continent: 'oceania' },
  {
    name: 'Venezuela, Bolivarian Republic of',
    shortCode: 'VE',
    code: 'VEN',
    continent: 'america',
  },
  { name: 'Viet Nam', shortCode: 'VN', code: 'VNM', continent: 'asia' },
  {
    name: 'Virgin Islands, British',
    shortCode: 'VG',
    code: 'VGB',
    continent: 'america',
  },
  {
    name: 'Virgin Islands, U.S.',
    shortCode: 'VI',
    code: 'VIR',
    continent: 'america',
  },
  {
    name: 'Wallis and Futuna',
    shortCode: 'WF',
    code: 'WLF',
    continent: 'oceania',
  },
  { name: 'Western Sahara', shortCode: 'EH', code: 'ESH', continent: 'africa' },
  { name: 'Yemen', shortCode: 'YE', code: 'YEM', continent: 'asia' },
  { name: 'Zambia', shortCode: 'ZM', code: 'ZMB', continent: 'africa' },
  { name: 'Zimbabwe', shortCode: 'ZW', code: 'ZWE', continent: 'africa' },
];
