name: 'cmg-api-dev'

services:
  postgres:
    container_name: api-db-dev
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=cmgapi'
      - 'POSTGRES_PASSWORD=localpassword'
      - 'POSTGRES_USER=cmgapi'
    ports:
      - '1001:5432'

  redis:
    container_name: redis
    image: 'redis:latest'
    ports:
      - '1002:6379'
