import { config } from 'dotenv';
import { join } from 'path';

// Load environment variables from .env.production
config({ path: join(__dirname, '../../.env.production') });

export const {
  APP_DATABASE_URL,
  APP_JWT_SECRET,
  AWS_SMTP_USER,
  AWS_SMTP_PASSWORD,
  APP_FROM_EMAIL,
  APP_FRONTEND_URL,
  AWS_S3_ACCESS_KEY_ID,
  AWS_S3_SECRET_ACCESS_KEY,
  AWS_S3_REGION,
  AWS_S3_BUCKET_NAME,
  AWS_S3_BUCKET_NAME_ROYALTIES,
  APP_DMB_USER,
  APP_DMB_PASS,
  FALLBACK_LANGUAGE,
  DB_POSTGRES_DB,
  DB_POSTGRES_PASSWORD,
  DB_POSTGRES_USER,
  APP_REDIS_HOST,
  APP_REDIS_PORT,
  ENV,
  VERSION,
} = process.env;

export default {
  APP_DATABASE_URL,
  APP_JWT_SECRET,
  AWS_SMTP_USER,
  AWS_SMTP_PASSWORD,
  APP_FROM_EMAIL,
  APP_FRONTEND_URL,
  AWS_S3_ACCESS_KEY_ID,
  AWS_S3_SECRET_ACCESS_KEY,
  AWS_S3_REGION,
  AWS_S3_BUCKET_NAME,
  AWS_S3_BUCKET_NAME_ROYALTIES,
  APP_DMB_USER,
  APP_DMB_PASS,
  FALLBACK_LANGUAGE,
  DB_POSTGRES_DB,
  DB_POSTGRES_PASSWORD,
  DB_POSTGRES_USER,
  APP_REDIS_HOST,
  APP_REDIS_PORT: parseInt(APP_REDIS_PORT, 10),
  ENV,
  VERSION,
};
